// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Completed   pgtype.Bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
